### ISSUE TITLE
Add clock/timer

### ISSUE THREAD

**Issue by eaglegamma** [worldsowisdom/LifePALETTE#11]
The HUD should include an indicator of time...

**Comment by cyanrealm** [comment]
What's exactly the time it indicate? System time, game start up time or object life time?

**Comment by eaglegamma** [comment]
Good question. The main information is the game running time, i.e. when the player starts the game the clock starts running from 00:00.00, and as long as the game is running the timer runs. It can additionally (simultaneously or as an option) show system time.

Object lifetime should only appear in the object's stats/profile...

**Comment by eaglegamma** [comment]
We now have a nice clock! :) Thank you @cyanrealm
